global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rss-server'
    static_configs:
      - targets: ['server:9464']
        labels:
          service: 'rss-reader'
